### ISSUE TITLE
pylint / pytest

### ISSUE THREAD

**Issue by hiaselhans** [airgproducts/euklid_rs#21]
@naschidaniel weisst du was da los is?

https://github.com/airgproducts/euklid_rs/runs/7007166969?check_suite_focus=true

:)

**Comment by naschidaniel** [comment]
@hiaselhans,

die Namen der wheels haben sich geändert. 
Der Grund dafür liegt bei der Konfiguration von der github-ci rust build Konfiguration.

https://github.com/airgproducts/euklid_rs/commit/e385a97ae8a85a04c92f389a96b52af089f6bfc4

Wie es scheint wurde manylinux in der github-ci aktualisiert.

Wenn ich `maturin build` lokal ausführe, dann erhalte ich folgendes wheel `euklid_rs-0.1.0-cp310-cp310-linux_x86_64.whl`.

Beste Grüße,

Daniel
